# Generated by Django 4.2 on 2023-04-20 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delyzer', '0002_departure_station_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='planned_departure',
        ),
        migrations.RemoveField(
            model_name='departure',
            name='real_departure',
        ),
        migrations.AddField(
            model_name='departure',
            name='current_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 15, 3, 54, 963601)),
        ),
        migrations.AddField(
            model_name='departure',
            name='destination_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='departure',
            name='direction',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='departure',
            name='direction_from',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='departure',
            name='planned_departure_time',
            field=models.TimeField(default=datetime.time(15, 3, 54, 963584)),
        ),
        migrations.AlterField(
            model_name='departure',
            name='delay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='departure',
            name='line_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='departure',
            name='line_number',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='departure',
            name='station_id',
            field=models.IntegerField(default=-1),
        ),
    ]
