# Generated by Django 4.2 on 2023-04-20 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delyzer', '0003_remove_departure_planned_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='current_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 15, 6, 7, 342948, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='departure',
            name='planned_departure_time',
            field=models.TimeField(default=datetime.time(15, 6, 7, 342787)),
        ),
    ]
