# Generated by Django 4.2 on 2023-04-20 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delyzer', '0004_alter_departure_current_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='current_date_time',
        ),
        migrations.AddField(
            model_name='departure',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 15, 6, 54, 641242, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='departure',
            name='planned_departure_time',
            field=models.TimeField(default=datetime.time(15, 6, 54, 641105)),
        ),
    ]
