# Generated by Django 4.2 on 2023-04-20 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delyzer', '0005_remove_departure_current_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 15, 9, 56, 723997, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='departure',
            name='planned_departure_time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 20, 15, 9, 56, 723825, tzinfo=datetime.timezone.utc)),
        ),
    ]
